import time
import random
print("\t Hacking Samuletor")
print("\t[+] Facebook Id Hacking\n\t[-] Instagram Id Hacking\n\t[*] Wifi Password Hacking\n\t[/] Password Genaretor\n\n")
print("Start hacking")
text=input("Enter Start hacking : \n")
text=str(text)
print("waite for few second..")
time.sleep(5)
print(text,"Successfull")
time.sleep(3)
print("Server connecting......")
time.sleep(0.5)
print("Server connecting..... 10%")
time.sleep(0.5)
print("Server connecting....20%")
time.sleep(0.5)
print("Server connecting....30%")
time.sleep(6)
print("Server connecting.....70%")
time.sleep(0.5)
print("Server connecting......90%")
time.sleep(9)
print("Server connecting ...... 100%")
time.sleep(0.5)
print("server connected......")
time.sleep(4)
print("Chooce one like +,-,*,/ : ")
oparetor=input("Enter one : ")
if oparetor=='+':
	print("\n\tWell come to Facebook Id hacking")
elif oparetor=='-':
	print("\n\tWellcome to Instagram Hacking")
elif oparetor=='*':
	print("\n\tWellcome to Wifi Password hacking")
elif oparetor=='/':
	print("\n\twellcome to Password Genaretor")
else:
	print("Invailed Chooce")
print("\n\tEnter Name / Id link ")
name=input()
name=str(name)
print("Hacking start....")
time.sleep(0.5)
print("Hacking 1%..")
time.sleep(0.5)
print("Hacking 2%..")
time.sleep(0.5)
print("Hacking 3%..")
time.sleep(0.5)
print("Hacking 4%..")
time.sleep(0.5)
print("Hacking 5%..")
time.sleep(0.5)
print("Hacking 6%..")
time.sleep(0.5)
print("Hacking 7%..")
time.sleep(0.5)
print("Hacking 8%..")
time.sleep(0.5)
print("Hacking 9%..")
time.sleep(0.5)
print("Hacking 10%..")
time.sleep(0.5)
print("Hacking 11%..")
time.sleep(0.5)
print("Hacking 12%..")
time.sleep(0.5)
print("Hacking 13%..")
time.sleep(0.5)
print("Hacking 14%..")
time.sleep(0.5)
print("Hacking 15%..")
time.sleep(0.5)
print("Hacking 16%..")
time.sleep(0.5)
print("Hacking 17%..")
time.sleep(0.5)
print("Hacking 18%..")
time.sleep(0.5)
print("Hacking 19%..")
time.sleep(0.5)
print("Hacking 20%..")
time.sleep(0.5)
print("Hacking 21%..")
time.sleep(0.5)
print("Hacking 22%..")
time.sleep(0.5)
print("Hacking 23%..")
time.sleep(0.5)
print("Hacking 24%..")
time.sleep(0.5)
print("Hacking 25%..")
time.sleep(0.5)
print("Hacking 26%..")
time.sleep(0.5)
print("Hacking 27%..")
time.sleep(0.5)
print("Hacking 28%..")
time.sleep(0.5)
print("Hacking 29%..")
time.sleep(0.5)
print("Hacking 30%..")
time.sleep(0.5)
print("Hacking 31%..")
time.sleep(0.5)
print("Hacking 32%..")
time.sleep(0.5)
print("Hacking 33%..")
time.sleep(0.5)
print("Hacking 34%..")
time.sleep(0.5)
print("Hacking 35%..")
time.sleep(0.5)
print("Hacking 36%..")
time.sleep(0.5)
print("Hacking 37%..")
time.sleep(0.5)
print("Hacking 38%..")
time.sleep(0.5)
print("Hacking 39%..")
time.sleep(0.5)
print("Hacking 40%..")
time.sleep(0.5)
print("Hacking 41%..")
time.sleep(0.5)
print("Hacking 42%..")
time.sleep(0.5)
print("Hacking 43%..")
time.sleep(0.5)
print("Hacking 44%..")
time.sleep(0.5)
print("Hacking 45%..")
time.sleep(0.5)
print("Hacking 46%..")
time.sleep(0.5)
print("Hacking 47%..")
time.sleep(0.5)
print("Hacking 48%..")
time.sleep(0.5)
print("Hacking 49%..")
time.sleep(0.5)
print("Hacking 50%..")
time.sleep(0.5)
print("Hacking 51%..")
time.sleep(0.5)
print("Hacking 52%..")
time.sleep(0.5)
print("Hacking 53%..")
time.sleep(0.5)
print("Hacking 54%..")
time.sleep(0.5)
print("Hacking 55%..")
time.sleep(0.5)
print("Hacking 56%..")
time.sleep(0.5)
print("Hacking 57%..")
time.sleep(0.5)
print("Hacking 58%..")
time.sleep(0.5)
print("Hacking 59%..")
time.sleep(0.5)
print("Hacking 60%..")
time.sleep(0.5)
print("Hacking 61%..")
time.sleep(0.5)
print("Hacking 62%..")
time.sleep(0.5)
print("Hacking 63%..")
time.sleep(0.5)
print("Hacking 64%..")
time.sleep(0.5)
print("Hacking 65%..")
time.sleep(0.5)
print("Hacking 66%..")
time.sleep(0.5)
print("Hacking 67%..")
time.sleep(0.5)
print("Hacking 68%..")
time.sleep(0.5)
print("Hacking 69%..")
time.sleep(0.5)
print("Hacking 70%..")
time.sleep(0.5)
print("Hacking 71%..")
time.sleep(0.5)
print("Hacking 72%..")
time.sleep(0.5)
print("Hacking 73%..")
time.sleep(0.5)
print("Hacking 74%..")
time.sleep(0.5)
print("Hacking 75%..")
time.sleep(0.5)
print("Hacking 76%..")
time.sleep(0.5)
print("Hacking 77%..")
time.sleep(0.5)
print("Hacking 78%..")
time.sleep(0.5)
print("Hacking 79%..")
time.sleep(0.5)
print("Hacking 80%..")
time.sleep(0.5)
print("Hacking 81%..")
time.sleep(0.5)
print("Hacking 82%..")
time.sleep(0.5)
print("Hacking 83%..")
time.sleep(0.5)
print("Hacking 84%..")
time.sleep(0.5)
print("Hacking 85%..")
time.sleep(0.5)
print("Hacking 86%..")
time.sleep(0.5)
print("Hacking 87%..")
time.sleep(0.5)
print("Hacking 88%..")
time.sleep(0.5)
print("Hacking 89%..")
time.sleep(0.5)
print("Hacking 90%..")
time.sleep(0.5)
print("Hacking 91%..")
time.sleep(0.5)
print("Hacking 92%..")
time.sleep(0.5)
print("Hacking 93%..")
time.sleep(0.5)
print("Hacking 94%..")
time.sleep(0.5)
print("Hacking 95%..")
time.sleep(0.5)
print("Hacking 96%..")
time.sleep(0.5)
print("Hacking 97%..")
time.sleep(0.5)
print("Hacking 98%..")
time.sleep(0.5)
print("Hacking 99%..")
time.sleep(5)
print("Hacking 100%..")
time.sleep(0.5)
if oparetor=='+':
	print(name,"Facebook Id Hacke successfull")
	print("Waite for few second.......")
	upper="ABCDEFGHIJKLMNOPQRSTUVWXYZ"
	lower="abcdefghijklmnopqrstuvwxyz"
	number="0123456789"
	symble="@#$/-=,.><"
	all=upper+lower+number+symble
	length=8
	password="".join(random.sample(all,length))
	time.sleep(5)
	print("Name : ",name)
	print("Password : ",password)
	
elif oparetor=='-':
	time.sleep(0.5)
	print(name,"Instagramm Id hacke success full")
	print("Waite for few second.......")
	upper="ABCDEFGHIJKLMNOPQRSTUVWXYZ"
	lower="abcdefghijklmnopqrstuvwxyz"
	number="0123456789"
	symble="@#$/-=,.><"
	all=upper+lower+number+symble
	length=8
	password="".join(random.sample(all,length))
	time.sleep(5)
	print("Name : ",name)
	print("Password : ",password)
elif oparetor=='*':
	time.sleep(0.5)
	print(name,"Wifi Hacke successfull")
	print("Waite for few second.......")
	upper="ABCDEFGHIJKLMNOPQRSTUVWXYZ"
	lower="abcdefghijklmnopqrstuvwxyz"
	number="0123456789"
	symble="@#$/-=,.><"
	all=upper+lower+number+symble
	length=8
	password="".join(random.sample(all,length))
	time.sleep(5)
	print("Name : ",name)
	print("Password : ",password)
elif oparetor=='/':
	time.sleep(0.5)
	print(name,"Password Genaret Successfull")
	print("Waite for few second.......")
	upper="ABCDEFGHIJKLMNOPQRSTUVWXYZ"
	lower="abcdefghijklmnopqrstuvwxyz"
	number="0123456789"
	symble="@#$/-=,.><"
	all=upper+lower+number+symble
	length=8
	password="".join(random.sample(all,length))
	time.sleep(5)
	print("Name : ",name)
	print("Password : ",password)
